package c2j

import c2j.antlrGenerated.CLexer

class CToJavaVocabulary {
    public static final def unsupportedPlaceholder = "\${statement}"
    private static final def unsupportedStatement = "Unsuported statement: $unsupportedPlaceholder"


    private static final Map<Integer, String> cToJavaVocabulary = [
            (CLexer.Break)           : "break",
            (CLexer.Case)            : "case",
            (CLexer.Char)            : "char",
            (CLexer.Const)           : "public static final",
            (CLexer.Continue)        : "continue",
            (CLexer.Default)         : "default",
            (CLexer.Do)              : "do",
            (CLexer.Double)          : "double",
            (CLexer.Else)            : "else ",
            (CLexer.Enum)            : "enum",
            (CLexer.Extern)          : "/* Replace extern declaration with proper Java import statement or implement other alternative. $unsupportedStatement */\n",
            (CLexer.Float)           : "float",
            (CLexer.For)             : "for",
            (CLexer.Goto)            : "/* Implement alternative to C goto statement. $unsupportedStatement */\n",
            (CLexer.If)              : "if",
            (CLexer.Inline)          : "",
            (CLexer.Int)             : "int",
            (CLexer.Long)            : "long",
            (CLexer.Register)        : "/* Warning. Register keyword omitted. */\n",
            (CLexer.Restrict)        : "/* inline specifier has been removed */\n",
            (CLexer.Return)          : "return",
            (CLexer.Short)           : "short",
            (CLexer.Signed)          : "/* signed keyword omitted. Java primitive types are signed by design. */\n",
            (CLexer.Sizeof)          : "/* Warning: C sizeof keyword is not supported */\n",
            (CLexer.Static)          : "/* Warning: C static keyword is not supported */\n",
            (CLexer.Struct)          : "public static class",
            (CLexer.Switch)          : "switch",
            (CLexer.Typedef)         : "/* Warning: typedef is not supported */\n",
            (CLexer.Union)           : "public static class",
            (CLexer.Unsigned)        : "/* Warning. Java does not support unsigned types. */\n",
            (CLexer.Void)            : "void",
            (CLexer.Volatile)        : "volatile",
            (CLexer.While)           : "while",
            (CLexer.Alignas)         : "/* Warning: _Alignas keyword does not have its equivalent in Java */\n",
            (CLexer.Alignof)         : "/* Warning: _Alignof keyword does not have its equivalent in Java */\n",
            (CLexer.Atomic)          : "/* Warning: C _Atomic keyword is not supported */\n",
            (CLexer.Bool)            : "boolean",
            (CLexer.Complex)         : "/* Warning: _Complex keyword does not have its equivalent in Java */\n",
            (CLexer.Generic)         : "",
            (CLexer.Imaginary)       : "/* Warning: _Imaginary keyword does not have its equivalent in Java */\n",
            (CLexer.Noreturn)        : "/* Warning: _Noreturn keyword does not have its equivalent in Java */\n",
            (CLexer.StaticAssert)    : "assert",
            (CLexer.ThreadLocal)     : "",
            (CLexer.LeftParen)       : "(",
            (CLexer.RightParen)      : ")",
            (CLexer.LeftBracket)     : "[",
            (CLexer.RightBracket)    : "]",
            (CLexer.LeftBrace)       : "{",
            (CLexer.RightBrace)      : "}",
            (CLexer.Less)            : "<",
            (CLexer.LessEqual)       : "<=",
            (CLexer.Greater)         : ">",
            (CLexer.GreaterEqual)    : ">=",
            (CLexer.LeftShift)       : "",
            (CLexer.RightShift)      : "",
            (CLexer.Plus)            : "+",
            (CLexer.PlusPlus)        : "++",
            (CLexer.Minus)           : "-",
            (CLexer.MinusMinus)      : "--",
            (CLexer.Star)            : "*",
            (CLexer.Div)             : "/",
            (CLexer.Mod)             : "%",
            (CLexer.And)             : "&",
            (CLexer.Or)              : "|",
            (CLexer.AndAnd)          : "&&",
            (CLexer.OrOr)            : "||",
            (CLexer.Caret)           : "^",
            (CLexer.Not)             : "!",
            (CLexer.Tilde)           : "~",
            (CLexer.Question)        : "?",
            (CLexer.Colon)           : ":",
            (CLexer.Semi)            : ";",
            (CLexer.Comma)           : ",",
            (CLexer.Assign)          : "=",
            (CLexer.StarAssign)      : "*=",
            (CLexer.DivAssign)       : "/=",
            (CLexer.ModAssign)       : "%=",
            (CLexer.PlusAssign)      : "+=",
            (CLexer.MinusAssign)     : "-=",
            (CLexer.LeftShiftAssign) : "<=",
            (CLexer.RightShiftAssign): ">=",
            (CLexer.AndAssign)       : "&=",
            (CLexer.XorAssign)       : "^=",
            (CLexer.OrAssign)        : "|=",
            (CLexer.Equal)           : "==",
            (CLexer.NotEqual)        : "!=",
            (CLexer.Arrow)           : ".",
            (CLexer.Dot)             : ".",
            (CLexer.Ellipsis)        : "/* Warning: C ellipsis argument is not supported */\n"
    ].asImmutable()


    static String translateFromCToJava(int tokenIndex) {
        return cToJavaVocabulary[tokenIndex]
    }
}
